-- tullaCTC configuration localization - English
local L = LibStub('AceLocale-3.0'):NewLocale('tullaCTC', 'enUS', true)

L.Anchor = 'Anchor'
L.Anchor_BOTTOM = 'Bottom'
L.Anchor_BOTTOMLEFT = 'Bottom Left'
L.Anchor_BOTTOMRIGHT = 'Bottom Right'
L.Anchor_CENTER = 'Center'
L.Anchor_LEFT = 'Left'
L.Anchor_RIGHT = 'Right'
L.Anchor_TOP = 'Top'
L.Anchor_TOPLEFT = 'Top Left'
L.Anchor_TOPRIGHT = 'Top Right'
L.Colors = 'Colors'
L.ColorsDesc = 'Configure text colors based on remaining cooldown time'
L.ColorsDescription = 'Set the color and duration threshold for each time range. Text will use the color for durations up to the threshold.'
L.CooldownText = 'Cooldown Text'
L.Duration = 'Duration'
L.FontFace = 'Font Face'
L.FontOutline = 'Font Outline'
L.FontSize = 'Font Size'
L.ForceShowText = 'Force show countdown text'
L.ForceShowTextDesc = 'Always display countdown text, even if the cooldown frame has it disabled'
L.General = GENERAL
L.HorizontalOffset = 'Horizontal Offset'
L.MinDuration = 'Minimum Duration'
L.MinDurationDesc = 'How long, in seconds, a cooldown must be to display countdown text'
L.AbbrevThreshold = 'Abbreviation Threshold'
L.AbbrevThresholdDesc = 'How long, in seconds, before cooldown text switches to abbreviated format (e.g., "1m" instead of "60")'
L.Outline_NONE = NONE
L.Outline_OUTLINE = 'Thin'
L.Outline_OUTLINEMONOCHROME = 'Monochrome'
L.Outline_THICKOUTLINE = 'Thick'
L.Preview = PREVIEW
L.TextColor = 'Text Color'
L.TextFont = 'Text Font'
L.TextPosition = 'Text Position'
L.TextShadow = 'Text Shadow'
L.TextShadowColor = COLOR
L.Themes = 'Themes'
L.ThemesDesc = 'Configure the appearance of cooldown countdown text'
L.NewThemeName = 'New Theme Name'
L.NewThemeNameDesc = 'Enter a name for the new theme'
L.CreateTheme = 'Create Theme'
L.CreateThemeDesc = 'Creates a new theme with the specified name'
L.DeleteTheme = DELETE
L.DeleteThemeDesc = 'Deletes the selected theme'
L.DeleteThemeConfirm = 'Are you sure you want to delete the theme "%s"?'
L.CannotDeleteDefault = 'Cannot delete the default theme'
L.CopyTheme = 'Copy Theme'
L.CopyThemeDesc = 'Make a copy of the current theme'
L.ResetTheme = 'Reset'
L.ResetThemeDesc = 'Resets current theme to default values'
L.ResetThemeConfirm = 'Are you sure you want to reset the theme "%s" to default values?'
L.RenameTheme = 'Rename'
L.RenameThemeDesc = 'Rename the selected theme'
L.SelectTheme = 'Theme'
L.ManageThemes = 'Themes'
L.ManageThemesDesc = 'Add, remove, and delete themes'
L.Threshold = 'Duration (Seconds)'
L.ThresholdDesc = 'Duration threshold for this color range'
L.Typography = 'Typography'
L.TypographyDesc = 'Configure font and text appearance'
L.VerticalOffset = 'Vertical Offset'

-- Color threshold UI
L.AddColorThreshold = 'Add Color Threshold'
L.NewThresholdValue = 'Threshold (seconds)'
L.NewThresholdValueDesc = "Enter threshold in seconds (e.g., 5, 60, 3600) or 'inf' for infinite"
L.RemoveThreshold = 'Remove'
L.RemoveThresholdConfirm = 'Remove this color threshold?'
L.ColorRangeForever = 'Forever'
L.ColorRangeDays = '%d day(s)'
L.ColorRangeHours = '%d hour(s)'
L.ColorRangeMinutes = '%d minute(s)'
L.ColorRangeSeconds = '%d second(s)'
L.ColorRangeAbove = 'Above %s'
L.ColorRangeUpTo = 'Up to %s'
L.ColorRangeBetween = '%s to %s'
L.ColorRangeAll = 'All durations'

-- Theme settings
L.ThemeEnabled = 'Enable Theme'
L.ThemeEnabledDesc = 'Apply this theme to matching cooldowns'
L.ThemeText = 'Style Countdown Text'
L.ThemeTextDesc = 'Apply text styling to cooldown counts'
L.ThemeCooldown = 'Style Cooldown Frames'
L.ThemeCooldownDesc = 'Apply cooldown frame specific styling options'

-- Cooldown display options
L.Cooldown = 'Cooldown'
L.CooldownDesc = 'Configure cooldown animation settings'
L.DrawText = 'Show Text'
L.DrawTextDesc = 'Control countdown text visibility'
L.DrawSwipe = 'Show Swipe'
L.DrawSwipeDesc = 'Control the radial swipe animation'
L.DrawEdge = 'Show Edge'
L.DrawEdgeDesc = 'Control the bright edge on the swipe'
L.DrawBling = 'Show Bling'
L.DrawBlingDesc = 'Control the flash effect when cooldown finishes'
L.Reverse = 'Reverse'
L.ReverseDesc = 'Reverse the swipe direction'

-- Tri-state values
L.DrawState_default = 'Default'
L.DrawState_always = 'Always'
L.DrawState_never = 'Never'

-- Rules
L.Rules = 'Rules'
L.RulesDesc = 'Configure which theme to apply to different UI elements'
L.RuleEnabled = 'Enabled'
L.RuleEnabledDesc = 'Enable or disable this rule'
L.RuleTheme = 'Theme'
L.RuleThemeDesc = 'Select which theme to apply when this rule matches'

-- Builtin Rule Names
L.Rule_action = 'Action Buttons'
L.Rule_action_charge = 'Action Buttons - Recharging'
L.Rule_action_loc = 'Action Buttons - Loss of Control'
L.Rule_blizzard_pet = 'Pet Bar'
L.Rule_blizzard_stance = 'Stance Bar'
L.Rule_blizzard_possess = 'Possess Bar'
L.Rule_blizzard_extra = 'Extra Action'
L.Rule_blizzard_zone = 'Zone Ability'
L.Rule_blizzard_target = 'Target Frame'
L.Rule_blizzard_container = 'Inventory'
L.Rule_everything = 'Everything Else'
