-- tullaCTC configuration localization - Latin American Spanish
local L = LibStub('AceLocale-3.0'):NewLocale('tullaCTC', 'esMX')
if not L then return end

L.Anchor = 'Posición'
L.Anchor_BOTTOM = 'Abajo'
L.Anchor_BOTTOMLEFT = 'Abajo a la izquierda'
L.Anchor_BOTTOMRIGHT = 'Abajo a la derecha'
L.Anchor_CENTER = 'Centro'
L.Anchor_LEFT = 'Izquierda'
L.Anchor_RIGHT = 'Derecha'
L.Anchor_TOP = 'Arriba'
L.Anchor_TOPLEFT = 'Arriba a la izquierda'
L.Anchor_TOPRIGHT = 'Arriba a la derecha'
L.Colors = 'Colores'
L.ColorsDesc = 'Configurar los colores del texto según el tiempo de reutilización restante'
L.ColorsDescription = 'Establece el color y el umbral de duración para cada rango de tiempo. El texto usará el color para duraciones hasta el umbral.'
L.CooldownText = 'Texto de reutilización'
L.Duration = 'Duración'
L.FontFace = 'Fuente'
L.FontOutline = 'Contorno del texto'
L.FontSize = 'Tamaño del texto'
L.HorizontalOffset = 'Desplazamiento horizontal'
L.MinDuration = 'Duración mínima'
L.MinDurationDesc = 'Cuánto tiempo, en segundos, debe durar una reutilización para mostrar el texto de cuenta regresiva'
L.AbbrevThreshold = 'Umbral de abreviación'
L.AbbrevThresholdDesc = 'Cuánto tiempo, en segundos, antes de que el texto cambie a formato abreviado (ej. "1m" en lugar de "60")'
L.Outline_OUTLINE = 'Fino'
L.Outline_OUTLINEMONOCHROME = 'Monocromo'
L.Outline_THICKOUTLINE = 'Grueso'
L.TextColor = 'Color de texto'
L.TextFont = 'Fuente del texto'
L.TextPosition = 'Posición del texto'
L.TextShadow = 'Sombra del texto'
L.Themes = 'Temas'
L.CreateTheme = 'Crear tema'
L.CreateThemeDesc = 'Crea un nuevo tema con el nombre especificado'
L.DeleteThemeDesc = 'Elimina el tema seleccionado'
L.CopyTheme = 'Copiar tema'
L.CopyThemeDesc = 'Crear una copia del tema actual'
L.ResetTheme = 'Restablecer'
L.ResetThemeDesc = 'Restablece el tema actual a los valores predeterminados'
L.RenameTheme = 'Renombrar'
L.RenameThemeDesc = 'Renombrar el tema seleccionado'
L.SelectTheme = 'Tema'
L.ManageThemes = 'Temas'
L.Threshold = 'Duración (segundos)'
L.ThresholdDesc = 'Umbral de duración para este rango de color'
L.Typography = 'Tipografía'
L.TypographyDesc = 'Configurar la fuente y apariencia del texto'
L.VerticalOffset = 'Desplazamiento vertical'
L.UseAuraDisplayTime = 'Usar tiempo de visualización de aura'
L.UseAuraDisplayTimeDesc = 'Este ajuste controla el redondeo de la duración. Siempre redondeará hacia abajo. Nunca redondeará hacia arriba'

-- Color threshold UI
L.AddColorThreshold = 'Añadir umbral de color'
L.NewThresholdValue = 'Umbral (segundos)'
L.NewThresholdValueDesc = 'Introduce el umbral en segundos (ej. 5, 60, 3600)'
L.RemoveThreshold = 'Eliminar'
L.RemoveThresholdConfirm = '¿Eliminar este umbral de color?'
L.ColorRangeDays = '%d día(s)'
L.ColorRangeHours = '%d hora(s)'
L.ColorRangeMinutes = '%d minuto(s)'
L.ColorRangeSeconds = '%d segundo(s)'
L.ColorRangeAbove = 'Superior a %s'
L.ColorRangeOrLess = '%s o menos'
L.ColorRangeTo = '%s a %s'
L.ColorRangeAll = 'Todas las duraciones'

-- Theme settings
L.ThemeEnabled = 'Activar tema'
L.ThemeEnabledDesc = 'Aplicar este tema a las reutilizaciones coincidentes'
L.ThemeText = 'Estilizar texto de cuenta regresiva'
L.ThemeTextDesc = 'Aplicar estilo de texto a las cuentas regresivas'
L.ThemeCooldown = 'Estilizar marcos de reutilización'
L.ThemeCooldownDesc = 'Aplicar opciones de estilo específicas del marco de reutilización'

-- Cooldown display options
L.Cooldown = 'Reutilización'
L.CooldownDesc = 'Configurar los ajustes de animación de reutilización'
L.DrawText = 'Mostrar texto'
L.DrawTextDesc = 'Controlar la visibilidad del texto de cuenta regresiva'
L.DrawSwipe = 'Mostrar barrido'
L.DrawSwipeDesc = 'Controlar la animación de barrido radial'
L.DrawEdge = 'Mostrar borde'
L.DrawEdgeDesc = 'Controlar el borde brillante del barrido'
L.DrawBling = 'Mostrar destello'
L.DrawBlingDesc = 'Controlar el efecto de destello cuando termina la reutilización'
L.Reverse = 'Invertir'
L.ReverseDesc = 'Invertir la dirección del barrido'
L.SwipeColor = 'Color de barrido'
L.SwipeColorDesc = 'Anular el color de la animación de barrido de reutilización'
L.ThemeSwipeColor = 'Anular color de barrido'

-- Tri-state values
L.DrawState_default = 'Predeterminado'
L.DrawState_always = 'Siempre'
L.DrawState_never = 'Nunca'

-- Rules
L.Rules = 'Reglas'
L.RulesDesc = 'Configurar qué tema aplicar a diferentes elementos de la interfaz'
L.RuleEnabled = 'Activado'
L.RuleEnabledDesc = 'Activar o desactivar esta regla'
L.RuleTheme = 'Tema'
L.RuleThemeDesc = 'Seleccionar qué tema aplicar cuando esta regla coincida'

-- Builtin Rule Names
L.Rule_action = 'Botones de acción'
L.Rule_action_charge = 'Botones de acción - Recarga'
L.Rule_action_loc = 'Botones de acción - Pérdida de control'
L.Rule_blizzard_zone = 'Habilidad de zona'
L.Rule_blizzard_nameplates = 'Placas de nombre'
L.Rule_everything = 'Todo lo demás'
