-- tullaCTC configuration localization - French
local L = LibStub('AceLocale-3.0'):NewLocale('tullaCTC', 'frFR')
if not L then return end

L.Anchor = 'Position'
L.Anchor_BOTTOM = 'Bas'
L.Anchor_BOTTOMLEFT = 'Bas gauche'
L.Anchor_BOTTOMRIGHT = 'Bas droite'
L.Anchor_CENTER = 'Centre'
L.Anchor_LEFT = 'Gauche'
L.Anchor_RIGHT = 'Droite'
L.Anchor_TOP = 'Haut'
L.Anchor_TOPLEFT = 'Haut gauche'
L.Anchor_TOPRIGHT = 'Haut droite'
L.Colors = 'Couleurs'
L.ColorsDesc = 'Configurer les couleurs du texte selon le temps de recharge restant'
L.ColorsDescription = 'Définir la couleur et le seuil de durée pour chaque plage de temps. Le texte utilisera la couleur pour les durées jusqu\'au seuil.'
L.CooldownText = 'Texte de recharge'
L.Duration = 'Durée'
L.FontFace = 'Police de caractères'
L.FontOutline = 'Contour de police'
L.FontSize = 'Taille de police'
L.HorizontalOffset = 'Décalage horizontal'
L.MinDuration = 'Durée minimale'
L.MinDurationDesc = 'Durée minimale, en secondes, d\'un temps de recharge pour afficher le texte du compte à rebours'
L.AbbrevThreshold = 'Seuil d\'abréviation'
L.AbbrevThresholdDesc = 'Durée, en secondes, avant que le texte passe au format abrégé (ex. "1m" au lieu de "60")'
L.Outline_OUTLINE = 'Fin'
L.Outline_OUTLINEMONOCHROME = 'Monochrome'
L.Outline_THICKOUTLINE = 'Épais'
L.TextColor = 'Couleur du texte'
L.TextFont = 'Police du texte'
L.TextPosition = 'Position du texte'
L.TextShadow = 'Ombre du texte'
L.Themes = 'Thèmes'
L.CreateTheme = 'Créer un thème'
L.CreateThemeDesc = 'Crée un nouveau thème avec le nom spécifié'
L.DeleteThemeDesc = 'Supprime le thème sélectionné'
L.CopyTheme = 'Copier le thème'
L.CopyThemeDesc = 'Créer une copie du thème actuel'
L.ResetTheme = 'Réinitialiser'
L.ResetThemeDesc = 'Réinitialise le thème actuel aux valeurs par défaut'
L.RenameTheme = 'Renommer'
L.RenameThemeDesc = 'Renommer le thème sélectionné'
L.SelectTheme = 'Thème'
L.ManageThemes = 'Thèmes'
L.Threshold = 'Durée (secondes)'
L.ThresholdDesc = 'Seuil de durée pour cette plage de couleur'
L.Typography = 'Typographie'
L.TypographyDesc = 'Configurer la police et l\'apparence du texte'
L.VerticalOffset = 'Décalage vertical'
L.UseAuraDisplayTime = 'Utiliser la durée d\'affichage de l\'aura'
L.UseAuraDisplayTimeDesc = 'Ce réglage contrôle l\'arrondi de la durée. Toujours arrondira vers le bas. Jamais arrondira vers le haut'

-- Color threshold UI
L.AddColorThreshold = 'Ajouter un seuil de couleur'
L.NewThresholdValue = 'Seuil (secondes)'
L.NewThresholdValueDesc = 'Entrer le seuil en secondes (ex. 5, 60, 3600)'
L.RemoveThreshold = 'Supprimer'
L.RemoveThresholdConfirm = 'Supprimer ce seuil de couleur ?'
L.ColorRangeDays = '%d jour(s)'
L.ColorRangeHours = '%d heure(s)'
L.ColorRangeMinutes = '%d minute(s)'
L.ColorRangeSeconds = '%d seconde(s)'
L.ColorRangeAbove = 'Au-dessus de %s'
L.ColorRangeOrLess = '%s ou moins'
L.ColorRangeTo = '%s à %s'
L.ColorRangeAll = 'Toutes les durées'

-- Theme settings
L.ThemeEnabled = 'Activer le thème'
L.ThemeEnabledDesc = 'Appliquer ce thème aux temps de recharge correspondants'
L.ThemeText = 'Styliser le texte du compte à rebours'
L.ThemeTextDesc = 'Appliquer le style de texte aux comptes à rebours'
L.ThemeCooldown = 'Styliser les cadres de recharge'
L.ThemeCooldownDesc = 'Appliquer les options de style spécifiques aux cadres de recharge'

-- Cooldown display options
L.Cooldown = 'Recharge'
L.CooldownDesc = 'Configurer les paramètres d\'animation de recharge'
L.DrawText = 'Afficher le texte'
L.DrawTextDesc = 'Contrôler la visibilité du texte du compte à rebours'
L.DrawSwipe = 'Afficher le balayage'
L.DrawSwipeDesc = 'Contrôler l\'animation de balayage radial'
L.DrawEdge = 'Afficher le bord'
L.DrawEdgeDesc = 'Contrôler le bord lumineux du balayage'
L.DrawBling = 'Afficher l\'éclat'
L.DrawBlingDesc = 'Contrôler l\'effet d\'éclat à la fin de la recharge'
L.Reverse = 'Inverser'
L.ReverseDesc = 'Inverser la direction du balayage'
L.SwipeColor = 'Couleur du balayage'
L.SwipeColorDesc = 'Remplacer la couleur de l\'animation de balayage de recharge'
L.ThemeSwipeColor = 'Remplacer la couleur du balayage'

-- Tri-state values
L.DrawState_default = 'Par défaut'
L.DrawState_always = 'Toujours'
L.DrawState_never = 'Jamais'

-- Rules
L.Rules = 'Règles'
L.RulesDesc = 'Configurer quel thème appliquer aux différents éléments de l\'interface'
L.RuleEnabled = 'Activé'
L.RuleEnabledDesc = 'Activer ou désactiver cette règle'
L.RuleTheme = 'Thème'
L.RuleThemeDesc = 'Sélectionner le thème à appliquer lorsque cette règle correspond'

-- Builtin Rule Names
L.Rule_action = 'Boutons d\'action'
L.Rule_action_charge = 'Boutons d\'action - Recharge'
L.Rule_action_loc = 'Boutons d\'action - Perte de contrôle'
L.Rule_blizzard_zone = 'Capacité de zone'
L.Rule_blizzard_nameplates = 'Barres de nom'
L.Rule_everything = 'Tout le reste'
