-- tullaCTC configuration localization - Italian
local L = LibStub('AceLocale-3.0'):NewLocale('tullaCTC', 'itIT')
if not L then return end

L.Anchor = 'Posizione'
L.Anchor_BOTTOM = 'In basso'
L.Anchor_BOTTOMLEFT = 'In basso a sinistra'
L.Anchor_BOTTOMRIGHT = 'In basso a destra'
L.Anchor_CENTER = 'Al centro'
L.Anchor_LEFT = 'A sinistra'
L.Anchor_RIGHT = 'A destra'
L.Anchor_TOP = 'In alto'
L.Anchor_TOPLEFT = 'In alto a sinistra'
L.Anchor_TOPRIGHT = 'In alto a destra'
L.Colors = 'Colori'
L.ColorsDesc = 'Configura i colori del testo in base al tempo di recupero rimanente'
L.ColorsDescription = 'Imposta il colore e la soglia di durata per ogni intervallo di tempo. Il testo userà il colore per le durate fino alla soglia.'
L.CooldownText = 'Testo di recupero'
L.Duration = 'Durata'
L.FontFace = 'Carattere'
L.FontOutline = 'Bordo del carattere'
L.FontSize = 'Dimensione del carattere'
L.HorizontalOffset = 'Spostamento orizzontale'
L.MinDuration = 'Durata minima'
L.MinDurationDesc = 'Quanto deve durare, in secondi, un tempo di recupero per mostrare il testo del conto alla rovescia'
L.AbbrevThreshold = 'Soglia di abbreviazione'
L.AbbrevThresholdDesc = 'Quanto tempo, in secondi, prima che il testo passi al formato abbreviato (es. "1m" invece di "60")'
L.Outline_OUTLINE = 'Sottile'
L.Outline_OUTLINEMONOCHROME = 'Monocromatico'
L.Outline_THICKOUTLINE = 'Spesso'
L.TextColor = 'Colore del testo'
L.TextFont = 'Tipo di carattere'
L.TextPosition = 'Posizione del testo'
L.TextShadow = 'Ombra del testo'
L.Themes = 'Temi'
L.CreateTheme = 'Crea tema'
L.CreateThemeDesc = 'Crea un nuovo tema con il nome specificato'
L.DeleteThemeDesc = 'Elimina il tema selezionato'
L.CopyTheme = 'Copia tema'
L.CopyThemeDesc = 'Crea una copia del tema attuale'
L.ResetTheme = 'Ripristina'
L.ResetThemeDesc = 'Ripristina il tema attuale ai valori predefiniti'
L.RenameTheme = 'Rinomina'
L.RenameThemeDesc = 'Rinomina il tema selezionato'
L.SelectTheme = 'Tema'
L.ManageThemes = 'Temi'
L.Threshold = 'Durata (secondi)'
L.ThresholdDesc = 'Soglia di durata per questo intervallo di colore'
L.Typography = 'Tipografia'
L.TypographyDesc = 'Configura il carattere e l\'aspetto del testo'
L.VerticalOffset = 'Spostamento verticale'
L.UseAuraDisplayTime = 'Usa il tempo di visualizzazione dell\'aura'
L.UseAuraDisplayTimeDesc = 'Questa impostazione controlla l\'arrotondamento della durata. Sempre arrotonda per difetto. Mai arrotonda per eccesso'

-- Color threshold UI
L.AddColorThreshold = 'Aggiungi soglia di colore'
L.NewThresholdValue = 'Soglia (secondi)'
L.NewThresholdValueDesc = 'Inserisci la soglia in secondi (es. 5, 60, 3600)'
L.RemoveThreshold = 'Rimuovi'
L.RemoveThresholdConfirm = 'Rimuovere questa soglia di colore?'
L.ColorRangeDays = '%d giorno/i'
L.ColorRangeHours = '%d ora/e'
L.ColorRangeMinutes = '%d minuto/i'
L.ColorRangeSeconds = '%d secondo/i'
L.ColorRangeAbove = 'Oltre %s'
L.ColorRangeOrLess = '%s o meno'
L.ColorRangeTo = '%s a %s'
L.ColorRangeAll = 'Tutte le durate'

-- Theme settings
L.ThemeEnabled = 'Attiva tema'
L.ThemeEnabledDesc = 'Applica questo tema ai tempi di recupero corrispondenti'
L.ThemeText = 'Stilizza testo del conto alla rovescia'
L.ThemeTextDesc = 'Applica lo stile del testo ai conti alla rovescia'
L.ThemeCooldown = 'Stilizza riquadri di recupero'
L.ThemeCooldownDesc = 'Applica le opzioni di stile specifiche dei riquadri di recupero'

-- Cooldown display options
L.Cooldown = 'Recupero'
L.CooldownDesc = 'Configura le impostazioni dell\'animazione di recupero'
L.DrawText = 'Mostra testo'
L.DrawTextDesc = 'Controlla la visibilità del testo del conto alla rovescia'
L.DrawSwipe = 'Mostra scorrimento'
L.DrawSwipeDesc = 'Controlla l\'animazione di scorrimento radiale'
L.DrawEdge = 'Mostra bordo'
L.DrawEdgeDesc = 'Controlla il bordo luminoso dello scorrimento'
L.DrawBling = 'Mostra lampo'
L.DrawBlingDesc = 'Controlla l\'effetto lampo al termine del recupero'
L.Reverse = 'Inverti'
L.ReverseDesc = 'Inverti la direzione dello scorrimento'
L.SwipeColor = 'Colore scorrimento'
L.SwipeColorDesc = 'Sostituisci il colore dell\'animazione di scorrimento del recupero'
L.ThemeSwipeColor = 'Sostituisci colore scorrimento'

-- Tri-state values
L.DrawState_default = 'Predefinito'
L.DrawState_always = 'Sempre'
L.DrawState_never = 'Mai'

-- Rules
L.Rules = 'Regole'
L.RulesDesc = 'Configura quale tema applicare ai diversi elementi dell\'interfaccia'
L.RuleEnabled = 'Attivato'
L.RuleEnabledDesc = 'Attiva o disattiva questa regola'
L.RuleTheme = 'Tema'
L.RuleThemeDesc = 'Seleziona quale tema applicare quando questa regola corrisponde'

-- Builtin Rule Names
L.Rule_action = 'Pulsanti d\'azione'
L.Rule_action_charge = 'Pulsanti d\'azione - Ricarica'
L.Rule_action_loc = 'Pulsanti d\'azione - Perdita di controllo'
L.Rule_blizzard_zone = 'Abilità di zona'
L.Rule_blizzard_nameplates = 'Targhette'
L.Rule_everything = 'Tutto il resto'
