-- tullaCTC configuration localization - Korean
local L = LibStub('AceLocale-3.0'):NewLocale('tullaCTC', 'koKR')
if not L then return end

L.Anchor = '위치'
L.Anchor_BOTTOM = '하단'
L.Anchor_BOTTOMLEFT = '좌측 하단'
L.Anchor_BOTTOMRIGHT = '우측 하단'
L.Anchor_CENTER = '중앙'
L.Anchor_LEFT = '좌측'
L.Anchor_RIGHT = '우측'
L.Anchor_TOP = '상단'
L.Anchor_TOPLEFT = '좌측 상단'
L.Anchor_TOPRIGHT = '우측 상단'
L.Colors = '색상'
L.ColorsDesc = '남은 재사용 대기시간에 따른 텍스트 색상 설정'
L.ColorsDescription = '각 시간 범위에 대한 색상과 지속시간 임계값을 설정합니다. 텍스트는 임계값까지의 지속시간에 해당 색상을 사용합니다.'
L.CooldownText = '재사용 대기시간 텍스트'
L.Duration = '지속시간'
L.FontFace = '글꼴'
L.FontOutline = '글꼴 외곽선'
L.FontSize = '글꼴 크기'
L.HorizontalOffset = 'X 위치'
L.MinDuration = '최소 지속시간'
L.MinDurationDesc = '카운트다운 텍스트를 표시하기 위한 최소 재사용 대기시간(초)'
L.AbbrevThreshold = '약어 임계값'
L.AbbrevThresholdDesc = '텍스트가 축약 형식으로 전환되기까지의 시간(초) (예: "60" 대신 "1m")'
L.Outline_OUTLINE = '얇게'
L.Outline_OUTLINEMONOCHROME = '모노크롬'
L.Outline_THICKOUTLINE = '두껍게'
L.TextColor = '텍스트 색상'
L.TextFont = '텍스트 글꼴'
L.TextPosition = '텍스트 위치'
L.TextShadow = '텍스트 그림자'
L.Themes = '테마'
L.CreateTheme = '테마 만들기'
L.CreateThemeDesc = '지정된 이름으로 새 테마를 만듭니다'
L.DeleteThemeDesc = '선택한 테마를 삭제합니다'
L.CopyTheme = '테마 복사'
L.CopyThemeDesc = '현재 테마의 사본을 만듭니다'
L.ResetTheme = '초기화'
L.ResetThemeDesc = '현재 테마를 기본값으로 초기화합니다'
L.RenameTheme = '이름 변경'
L.RenameThemeDesc = '선택한 테마의 이름을 변경합니다'
L.SelectTheme = '테마'
L.ManageThemes = '테마'
L.Threshold = '지속시간 (초)'
L.ThresholdDesc = '이 색상 범위의 지속시간 임계값'
L.Typography = '타이포그래피'
L.TypographyDesc = '글꼴 및 텍스트 모양 설정'
L.VerticalOffset = 'Y 위치'
L.UseAuraDisplayTime = '오라 지속시간 표시 사용'
L.UseAuraDisplayTimeDesc = '이 설정은 지속시간 반올림을 제어합니다. 항상은 내림합니다. 안 함은 올림합니다'

-- Color threshold UI
L.AddColorThreshold = '색상 임계값 추가'
L.NewThresholdValue = '임계값 (초)'
L.NewThresholdValueDesc = '임계값을 초 단위로 입력 (예: 5, 60, 3600)'
L.RemoveThreshold = '제거'
L.RemoveThresholdConfirm = '이 색상 임계값을 제거하시겠습니까?'
L.ColorRangeDays = '%d일'
L.ColorRangeHours = '%d시간'
L.ColorRangeMinutes = '%d분'
L.ColorRangeSeconds = '%d초'
L.ColorRangeAbove = '%s 초과'
L.ColorRangeOrLess = '%s 이하'
L.ColorRangeTo = '%s ~ %s'
L.ColorRangeAll = '모든 지속시간'

-- Theme settings
L.ThemeEnabled = '테마 활성화'
L.ThemeEnabledDesc = '일치하는 재사용 대기시간에 이 테마를 적용합니다'
L.ThemeText = '카운트다운 텍스트 스타일'
L.ThemeTextDesc = '재사용 대기시간 카운트다운에 텍스트 스타일을 적용합니다'
L.ThemeCooldown = '재사용 대기시간 프레임 스타일'
L.ThemeCooldownDesc = '재사용 대기시간 프레임 관련 스타일 옵션을 적용합니다'

-- Cooldown display options
L.Cooldown = '재사용 대기시간'
L.CooldownDesc = '재사용 대기시간 애니메이션 설정'
L.DrawText = '텍스트 표시'
L.DrawTextDesc = '카운트다운 텍스트 표시 여부 제어'
L.DrawSwipe = '쓸기 표시'
L.DrawSwipeDesc = '방사형 쓸기 애니메이션 제어'
L.DrawEdge = '가장자리 표시'
L.DrawEdgeDesc = '쓸기의 밝은 가장자리 제어'
L.DrawBling = '반짝임 표시'
L.DrawBlingDesc = '재사용 대기시간 완료 시 반짝임 효과 제어'
L.Reverse = '역방향'
L.ReverseDesc = '쓸기 방향 반전'
L.SwipeColor = '쓸기 색상'
L.SwipeColorDesc = '재사용 대기시간 쓸기 애니메이션 색상 덮어쓰기'
L.ThemeSwipeColor = '쓸기 색상 덮어쓰기'

-- Tri-state values
L.DrawState_default = '기본값'
L.DrawState_always = '항상'
L.DrawState_never = '안 함'

-- Rules
L.Rules = '규칙'
L.RulesDesc = '다양한 UI 요소에 적용할 테마 설정'
L.RuleEnabled = '활성화'
L.RuleEnabledDesc = '이 규칙 활성화 또는 비활성화'
L.RuleTheme = '테마'
L.RuleThemeDesc = '이 규칙이 일치할 때 적용할 테마 선택'

-- Builtin Rule Names
L.Rule_action = '행동 단축 버튼'
L.Rule_action_charge = '행동 단축 버튼 - 충전'
L.Rule_action_loc = '행동 단축 버튼 - 제어 상실'
L.Rule_blizzard_zone = '지역 능력'
L.Rule_blizzard_nameplates = '이름표'
L.Rule_everything = '기타 모든 항목'
