-- tullaCTC configuration localization - Brazilian Portuguese
local L = LibStub('AceLocale-3.0'):NewLocale('tullaCTC', 'ptBR')
if not L then return end

L.Anchor = 'Posição'
L.Anchor_BOTTOM = 'Inferior'
L.Anchor_BOTTOMLEFT = 'Inferior esquerdo'
L.Anchor_BOTTOMRIGHT = 'Inferior direito'
L.Anchor_CENTER = 'Centro'
L.Anchor_LEFT = 'Esquerda'
L.Anchor_RIGHT = 'Direita'
L.Anchor_TOP = 'Superior'
L.Anchor_TOPLEFT = 'Superior esquerdo'
L.Anchor_TOPRIGHT = 'Superior direito'
L.Colors = 'Cores'
L.ColorsDesc = 'Configurar as cores do texto com base no tempo de recarga restante'
L.ColorsDescription = 'Defina a cor e o limite de duração para cada faixa de tempo. O texto usará a cor para durações até o limite.'
L.CooldownText = 'Texto de recarga'
L.Duration = 'Duração'
L.FontFace = 'Tipo de fonte'
L.FontOutline = 'Contorno da fonte'
L.FontSize = 'Tamanho da fonte'
L.HorizontalOffset = 'Deslocamento horizontal'
L.MinDuration = 'Duração mínima'
L.MinDurationDesc = 'Quanto tempo, em segundos, uma recarga deve ter para exibir o texto de contagem regressiva'
L.AbbrevThreshold = 'Limite de abreviação'
L.AbbrevThresholdDesc = 'Quanto tempo, em segundos, antes do texto mudar para formato abreviado (ex. "1m" em vez de "60")'
L.Outline_OUTLINE = 'Fino'
L.Outline_OUTLINEMONOCHROME = 'Monocromático'
L.Outline_THICKOUTLINE = 'Grosso'
L.TextColor = 'Cor do texto'
L.TextFont = 'Fonte do texto'
L.TextPosition = 'Posição do texto'
L.TextShadow = 'Sombra do texto'
L.Themes = 'Temas'
L.CreateTheme = 'Criar tema'
L.CreateThemeDesc = 'Cria um novo tema com o nome especificado'
L.DeleteThemeDesc = 'Exclui o tema selecionado'
L.CopyTheme = 'Copiar tema'
L.CopyThemeDesc = 'Criar uma cópia do tema atual'
L.ResetTheme = 'Redefinir'
L.ResetThemeDesc = 'Redefine o tema atual para os valores padrão'
L.RenameTheme = 'Renomear'
L.RenameThemeDesc = 'Renomear o tema selecionado'
L.SelectTheme = 'Tema'
L.ManageThemes = 'Temas'
L.Threshold = 'Duração (segundos)'
L.ThresholdDesc = 'Limite de duração para esta faixa de cor'
L.Typography = 'Tipografia'
L.TypographyDesc = 'Configurar a fonte e aparência do texto'
L.VerticalOffset = 'Deslocamento vertical'
L.UseAuraDisplayTime = 'Usar tempo de exibição de aura'
L.UseAuraDisplayTimeDesc = 'Esta configuração controla o arredondamento da duração. Sempre arredonda para baixo. Nunca arredonda para cima'

-- Color threshold UI
L.AddColorThreshold = 'Adicionar limite de cor'
L.NewThresholdValue = 'Limite (segundos)'
L.NewThresholdValueDesc = 'Insira o limite em segundos (ex. 5, 60, 3600)'
L.RemoveThreshold = 'Remover'
L.RemoveThresholdConfirm = 'Remover este limite de cor?'
L.ColorRangeDays = '%d dia(s)'
L.ColorRangeHours = '%d hora(s)'
L.ColorRangeMinutes = '%d minuto(s)'
L.ColorRangeSeconds = '%d segundo(s)'
L.ColorRangeAbove = 'Acima de %s'
L.ColorRangeOrLess = '%s ou menos'
L.ColorRangeTo = '%s a %s'
L.ColorRangeAll = 'Todas as durações'

-- Theme settings
L.ThemeEnabled = 'Ativar tema'
L.ThemeEnabledDesc = 'Aplicar este tema às recargas correspondentes'
L.ThemeText = 'Estilizar texto de contagem regressiva'
L.ThemeTextDesc = 'Aplicar estilo de texto às contagens regressivas'
L.ThemeCooldown = 'Estilizar quadros de recarga'
L.ThemeCooldownDesc = 'Aplicar opções de estilo específicas do quadro de recarga'

-- Cooldown display options
L.Cooldown = 'Recarga'
L.CooldownDesc = 'Configurar as opções de animação de recarga'
L.DrawText = 'Mostrar texto'
L.DrawTextDesc = 'Controlar a visibilidade do texto de contagem regressiva'
L.DrawSwipe = 'Mostrar varredura'
L.DrawSwipeDesc = 'Controlar a animação de varredura radial'
L.DrawEdge = 'Mostrar borda'
L.DrawEdgeDesc = 'Controlar a borda brilhante da varredura'
L.DrawBling = 'Mostrar brilho'
L.DrawBlingDesc = 'Controlar o efeito de brilho quando a recarga termina'
L.Reverse = 'Inverter'
L.ReverseDesc = 'Inverter a direção da varredura'
L.SwipeColor = 'Cor da varredura'
L.SwipeColorDesc = 'Substituir a cor da animação de varredura da recarga'
L.ThemeSwipeColor = 'Substituir cor da varredura'

-- Tri-state values
L.DrawState_default = 'Padrão'
L.DrawState_always = 'Sempre'
L.DrawState_never = 'Nunca'

-- Rules
L.Rules = 'Regras'
L.RulesDesc = 'Configurar qual tema aplicar a diferentes elementos da interface'
L.RuleEnabled = 'Ativado'
L.RuleEnabledDesc = 'Ativar ou desativar esta regra'
L.RuleTheme = 'Tema'
L.RuleThemeDesc = 'Selecionar qual tema aplicar quando esta regra corresponder'

-- Builtin Rule Names
L.Rule_action = 'Botões de ação'
L.Rule_action_charge = 'Botões de ação - Recarga'
L.Rule_action_loc = 'Botões de ação - Perda de controle'
L.Rule_blizzard_zone = 'Habilidade de zona'
L.Rule_blizzard_nameplates = 'Placas de identificação'
L.Rule_everything = 'Todo o resto'
