-- tullaCTC configuration localization - Russian
local L = LibStub('AceLocale-3.0'):NewLocale('tullaCTC', 'ruRU')
if not L then return end

L.Anchor = 'Привязка'
L.Anchor_BOTTOM = 'Внизу'
L.Anchor_BOTTOMLEFT = 'Внизу слева'
L.Anchor_BOTTOMRIGHT = 'Внизу справа'
L.Anchor_CENTER = 'По центру'
L.Anchor_LEFT = 'Слева'
L.Anchor_RIGHT = 'Справа'
L.Anchor_TOP = 'Вверху'
L.Anchor_TOPLEFT = 'Вверху слева'
L.Anchor_TOPRIGHT = 'Вверху справа'
L.Colors = 'Цвета'
L.ColorsDesc = 'Настройка цветов текста в зависимости от оставшегося времени восстановления'
L.ColorsDescription = 'Установите цвет и порог продолжительности для каждого временного диапазона. Текст будет использовать цвет для продолжительностей до порогового значения.'
L.CooldownText = 'Текст восстановления'
L.Duration = 'Длительность'
L.FontFace = 'Шрифт'
L.FontOutline = 'Контур шрифта'
L.FontSize = 'Размер шрифта'
L.HorizontalOffset = 'Горизонтальное смещение'
L.MinDuration = 'Минимальная длительность'
L.MinDurationDesc = 'Минимальная длительность восстановления в секундах для отображения текста обратного отсчёта'
L.AbbrevThreshold = 'Порог сокращения'
L.AbbrevThresholdDesc = 'Через сколько секунд текст переключится на сокращённый формат (например, "1м" вместо "60")'
L.Outline_OUTLINE = 'Тонкий'
L.Outline_OUTLINEMONOCHROME = 'Одноцветный'
L.Outline_THICKOUTLINE = 'Толстый'
L.TextColor = 'Цвет текста'
L.TextFont = 'Шрифт текста'
L.TextPosition = 'Расположение текста'
L.TextShadow = 'Тень текста'
L.Themes = 'Темы'
L.CreateTheme = 'Создать тему'
L.CreateThemeDesc = 'Создаёт новую тему с указанным именем'
L.DeleteThemeDesc = 'Удаляет выбранную тему'
L.CopyTheme = 'Копировать тему'
L.CopyThemeDesc = 'Создать копию текущей темы'
L.ResetTheme = 'Сбросить'
L.ResetThemeDesc = 'Сбрасывает текущую тему к значениям по умолчанию'
L.RenameTheme = 'Переименовать'
L.RenameThemeDesc = 'Переименовать выбранную тему'
L.SelectTheme = 'Тема'
L.ManageThemes = 'Темы'
L.Threshold = 'Длительность (секунды)'
L.ThresholdDesc = 'Порог длительности для этого цветового диапазона'
L.Typography = 'Типографика'
L.TypographyDesc = 'Настройка шрифта и внешнего вида текста'
L.VerticalOffset = 'Вертикальное смещение'
L.UseAuraDisplayTime = 'Использовать время отображения ауры'
L.UseAuraDisplayTimeDesc = 'Этот параметр управляет округлением длительности. Всегда округляет вниз. Никогда округляет вверх'

-- Color threshold UI
L.AddColorThreshold = 'Добавить цветовой порог'
L.NewThresholdValue = 'Порог (секунды)'
L.NewThresholdValueDesc = 'Введите порог в секундах (например, 5, 60, 3600)'
L.RemoveThreshold = 'Удалить'
L.RemoveThresholdConfirm = 'Удалить этот цветовой порог?'
L.ColorRangeDays = '%d дн.'
L.ColorRangeHours = '%d ч.'
L.ColorRangeMinutes = '%d мин.'
L.ColorRangeSeconds = '%d сек.'
L.ColorRangeAbove = 'Больше %s'
L.ColorRangeOrLess = '%s или менее'
L.ColorRangeTo = '%s до %s'
L.ColorRangeAll = 'Все длительности'

-- Theme settings
L.ThemeEnabled = 'Включить тему'
L.ThemeEnabledDesc = 'Применить эту тему к соответствующим восстановлениям'
L.ThemeText = 'Стилизовать текст отсчёта'
L.ThemeTextDesc = 'Применить стиль текста к обратным отсчётам'
L.ThemeCooldown = 'Стилизовать рамки восстановления'
L.ThemeCooldownDesc = 'Применить параметры стиля рамок восстановления'

-- Cooldown display options
L.Cooldown = 'Восстановление'
L.CooldownDesc = 'Настройка параметров анимации восстановления'
L.DrawText = 'Показать текст'
L.DrawTextDesc = 'Управление видимостью текста обратного отсчёта'
L.DrawSwipe = 'Показать затемнение'
L.DrawSwipeDesc = 'Управление радиальной анимацией затемнения'
L.DrawEdge = 'Показать край'
L.DrawEdgeDesc = 'Управление светящимся краем затемнения'
L.DrawBling = 'Показать вспышку'
L.DrawBlingDesc = 'Управление эффектом вспышки при завершении восстановления'
L.Reverse = 'Обратить'
L.ReverseDesc = 'Обратить направление затемнения'
L.SwipeColor = 'Цвет затемнения'
L.SwipeColorDesc = 'Заменить цвет анимации затемнения восстановления'
L.ThemeSwipeColor = 'Заменить цвет затемнения'

-- Tri-state values
L.DrawState_default = 'По умолчанию'
L.DrawState_always = 'Всегда'
L.DrawState_never = 'Никогда'

-- Rules
L.Rules = 'Правила'
L.RulesDesc = 'Настройка темы для различных элементов интерфейса'
L.RuleEnabled = 'Включено'
L.RuleEnabledDesc = 'Включить или отключить это правило'
L.RuleTheme = 'Тема'
L.RuleThemeDesc = 'Выбрать тему для применения при совпадении этого правила'

-- Builtin Rule Names
L.Rule_action = 'Кнопки действий'
L.Rule_action_charge = 'Кнопки действий - Перезарядка'
L.Rule_action_loc = 'Кнопки действий - Потеря контроля'
L.Rule_blizzard_zone = 'Способность зоны'
L.Rule_blizzard_nameplates = 'Индикаторы здоровья'
L.Rule_everything = 'Всё остальное'
