-- tullaCTC configuration localization - Simplified Chinese
local L = LibStub('AceLocale-3.0'):NewLocale('tullaCTC', 'zhCN')
if not L then return end

L.Anchor = '锚点'
L.Anchor_BOTTOM = '下'
L.Anchor_BOTTOMLEFT = '左下'
L.Anchor_BOTTOMRIGHT = '右下'
L.Anchor_CENTER = '中'
L.Anchor_LEFT = '左'
L.Anchor_RIGHT = '右'
L.Anchor_TOP = '上'
L.Anchor_TOPLEFT = '左上'
L.Anchor_TOPRIGHT = '右上'
L.Colors = '颜色'
L.ColorsDesc = '根据剩余冷却时间配置文字颜色'
L.ColorsDescription = '为每个时间范围设置颜色和持续时间阈值。文字将使用对应颜色显示至阈值的持续时间。'
L.CooldownText = '冷却文字'
L.Duration = '持续时间'
L.FontFace = '字体'
L.FontOutline = '字体轮廓'
L.FontSize = '字体大小'
L.HorizontalOffset = '水平偏移'
L.MinDuration = '最短持续时间'
L.MinDurationDesc = '冷却时间需要多长（秒）才会显示倒计时文字'
L.AbbrevThreshold = '缩写阈值'
L.AbbrevThresholdDesc = '冷却文字切换到缩写格式之前的时间（秒）（例如用"1m"代替"60"）'
L.Outline_OUTLINE = '细边'
L.Outline_OUTLINEMONOCHROME = '无抗锯齿'
L.Outline_THICKOUTLINE = '粗边'
L.TextColor = '文字颜色'
L.TextFont = '文字字体'
L.TextPosition = '文字位置'
L.TextShadow = '文字阴影'
L.Themes = '主题'
L.CreateTheme = '创建主题'
L.CreateThemeDesc = '使用指定名称创建新主题'
L.DeleteThemeDesc = '删除选中的主题'
L.CopyTheme = '复制主题'
L.CopyThemeDesc = '创建当前主题的副本'
L.ResetTheme = '重置'
L.ResetThemeDesc = '将当前主题重置为默认值'
L.RenameTheme = '重命名'
L.RenameThemeDesc = '重命名选中的主题'
L.SelectTheme = '主题'
L.ManageThemes = '主题'
L.Threshold = '持续时间（秒）'
L.ThresholdDesc = '此颜色范围的持续时间阈值'
L.Typography = '字体样式'
L.TypographyDesc = '配置字体和文字外观'
L.VerticalOffset = '垂直偏移'
L.UseAuraDisplayTime = '使用光环持续时间显示'
L.UseAuraDisplayTimeDesc = '此设置控制持续时间的取整方式。始终将向下取整。从不将向上取整'

-- Color threshold UI
L.AddColorThreshold = '添加颜色阈值'
L.NewThresholdValue = '阈值（秒）'
L.NewThresholdValueDesc = '输入阈值（秒）（例如 5、60、3600）'
L.RemoveThreshold = '移除'
L.RemoveThresholdConfirm = '移除此颜色阈值？'
L.ColorRangeDays = '%d天'
L.ColorRangeHours = '%d小时'
L.ColorRangeMinutes = '%d分钟'
L.ColorRangeSeconds = '%d秒'
L.ColorRangeAbove = '超过%s'
L.ColorRangeOrLess = '%s或更少'
L.ColorRangeTo = '%s到%s'
L.ColorRangeAll = '所有持续时间'

-- Theme settings
L.ThemeEnabled = '启用主题'
L.ThemeEnabledDesc = '将此主题应用到匹配的冷却'
L.ThemeText = '设置倒计时文字样式'
L.ThemeTextDesc = '将文字样式应用到冷却倒计时'
L.ThemeCooldown = '设置冷却框架样式'
L.ThemeCooldownDesc = '应用冷却框架特定的样式选项'

-- Cooldown display options
L.Cooldown = '冷却'
L.CooldownDesc = '配置冷却动画设置'
L.DrawText = '显示文字'
L.DrawTextDesc = '控制倒计时文字的可见性'
L.DrawSwipe = '显示扫过效果'
L.DrawSwipeDesc = '控制径向扫过动画'
L.DrawEdge = '显示边缘'
L.DrawEdgeDesc = '控制扫过效果的明亮边缘'
L.DrawBling = '显示闪光'
L.DrawBlingDesc = '控制冷却结束时的闪光效果'
L.Reverse = '反转'
L.ReverseDesc = '反转扫过方向'
L.SwipeColor = '扫过颜色'
L.SwipeColorDesc = '覆盖冷却扫过动画的颜色'
L.ThemeSwipeColor = '覆盖扫过颜色'

-- Tri-state values
L.DrawState_default = '默认'
L.DrawState_always = '始终'
L.DrawState_never = '从不'

-- Rules
L.Rules = '规则'
L.RulesDesc = '配置将哪个主题应用到不同的界面元素'
L.RuleEnabled = '已启用'
L.RuleEnabledDesc = '启用或禁用此规则'
L.RuleTheme = '主题'
L.RuleThemeDesc = '选择此规则匹配时要应用的主题'

-- Builtin Rule Names
L.Rule_action = '动作按钮'
L.Rule_action_charge = '动作按钮 - 充能'
L.Rule_action_loc = '动作按钮 - 失去控制'
L.Rule_blizzard_zone = '区域技能'
L.Rule_blizzard_nameplates = '姓名板'
L.Rule_everything = '其他所有'
