-- tullaCTC configuration localization - Chinese Simplified
local L = LibStub("AceLocale-3.0"):NewLocale("tullaCTC", "zhCN")
if not L then return end

L.Anchor = '锚点'
L.Anchor_BOTTOM = '下'
L.Anchor_BOTTOMLEFT = '左下'
L.Anchor_BOTTOMRIGHT = '右下'
L.Anchor_CENTER = '中'
L.Anchor_LEFT = '左'
L.Anchor_RIGHT = '右'
L.Anchor_TOP = '上'
L.Anchor_TOPLEFT = '左上'
L.Anchor_TOPRIGHT = '右上'
L.CooldownText = '冷却文字'
L.FontFace = '字体风格'
L.FontOutline = '字体轮廓'
L.FontSize = '字体大小'
L.HorizontalOffset = '水平偏移'
L.MinDuration = '显示文字的最少时间'
L.Outline_NONE = '无'
L.Outline_OUTLINE = '细边'
L.Outline_OUTLINEMONOCHROME = '无抗锯齿'
L.Outline_THICKOUTLINE = '粗边'
L.TextColor = '字体颜色'
L.TextFont = '字体'
L.TextPosition = '文字位置'
L.TextShadow = '文字阴影'
L.TextShadowColor = '颜色'
L.Themes = '主题'
L.Typography = '字体式样'
L.VerticalOffset = '垂直偏移量'
