-- tullaCTC configuration localization - Traditional Chinese
local L = LibStub('AceLocale-3.0'):NewLocale('tullaCTC', 'zhTW')
if not L then return end

L.Anchor = '錨點'
L.Anchor_BOTTOM = '下'
L.Anchor_BOTTOMLEFT = '左下'
L.Anchor_BOTTOMRIGHT = '右下'
L.Anchor_CENTER = '中'
L.Anchor_LEFT = '左'
L.Anchor_RIGHT = '右'
L.Anchor_TOP = '上'
L.Anchor_TOPLEFT = '左上'
L.Anchor_TOPRIGHT = '右上'
L.Colors = '顏色'
L.ColorsDesc = '根據剩餘冷卻時間設定文字顏色'
L.ColorsDescription = '為每個時間範圍設定顏色和持續時間門檻。文字將使用對應顏色顯示至門檻的持續時間。'
L.CooldownText = '冷卻文字'
L.Duration = '持續時間'
L.FontFace = '字型'
L.FontOutline = '字型輪廓'
L.FontSize = '字型大小'
L.HorizontalOffset = '水平偏移'
L.MinDuration = '最短持續時間'
L.MinDurationDesc = '冷卻時間需要多長（秒）才會顯示倒數文字'
L.AbbrevThreshold = '縮寫門檻'
L.AbbrevThresholdDesc = '冷卻文字切換到縮寫格式之前的時間（秒）（例如用「1m」代替「60」）'
L.Outline_OUTLINE = '細邊'
L.Outline_OUTLINEMONOCHROME = '無抗鋸齒'
L.Outline_THICKOUTLINE = '粗邊'
L.TextColor = '文字顏色'
L.TextFont = '文字字型'
L.TextPosition = '文字位置'
L.TextShadow = '文字陰影'
L.Themes = '主題'
L.CreateTheme = '建立主題'
L.CreateThemeDesc = '使用指定名稱建立新主題'
L.DeleteThemeDesc = '刪除選取的主題'
L.CopyTheme = '複製主題'
L.CopyThemeDesc = '建立目前主題的副本'
L.ResetTheme = '重設'
L.ResetThemeDesc = '將目前主題重設為預設值'
L.RenameTheme = '重新命名'
L.RenameThemeDesc = '重新命名選取的主題'
L.SelectTheme = '主題'
L.ManageThemes = '主題'
L.Threshold = '持續時間（秒）'
L.ThresholdDesc = '此顏色範圍的持續時間門檻'
L.Typography = '文字式樣'
L.TypographyDesc = '設定字型和文字外觀'
L.VerticalOffset = '垂直偏移'
L.UseAuraDisplayTime = '使用光環持續時間顯示'
L.UseAuraDisplayTimeDesc = '此設定控制持續時間的取整方式。始終將向下取整。從不將向上取整'

-- Color threshold UI
L.AddColorThreshold = '新增顏色門檻'
L.NewThresholdValue = '門檻（秒）'
L.NewThresholdValueDesc = '輸入門檻（秒）（例如 5、60、3600）'
L.RemoveThreshold = '移除'
L.RemoveThresholdConfirm = '移除此顏色門檻？'
L.ColorRangeDays = '%d天'
L.ColorRangeHours = '%d小時'
L.ColorRangeMinutes = '%d分鐘'
L.ColorRangeSeconds = '%d秒'
L.ColorRangeAbove = '超過%s'
L.ColorRangeOrLess = '%s或更少'
L.ColorRangeTo = '%s到%s'
L.ColorRangeAll = '所有持續時間'

-- Theme settings
L.ThemeEnabled = '啟用主題'
L.ThemeEnabledDesc = '將此主題套用到符合的冷卻'
L.ThemeText = '設定倒數文字樣式'
L.ThemeTextDesc = '將文字樣式套用到冷卻倒數'
L.ThemeCooldown = '設定冷卻框架樣式'
L.ThemeCooldownDesc = '套用冷卻框架特定的樣式選項'

-- Cooldown display options
L.Cooldown = '冷卻'
L.CooldownDesc = '設定冷卻動畫'
L.DrawText = '顯示文字'
L.DrawTextDesc = '控制倒數文字的可見性'
L.DrawSwipe = '顯示掃過效果'
L.DrawSwipeDesc = '控制徑向掃過動畫'
L.DrawEdge = '顯示邊緣'
L.DrawEdgeDesc = '控制掃過效果的明亮邊緣'
L.DrawBling = '顯示閃光'
L.DrawBlingDesc = '控制冷卻結束時的閃光效果'
L.Reverse = '反轉'
L.ReverseDesc = '反轉掃過方向'
L.SwipeColor = '掃過顏色'
L.SwipeColorDesc = '覆蓋冷卻掃過動畫的顏色'
L.ThemeSwipeColor = '覆蓋掃過顏色'

-- Tri-state values
L.DrawState_default = '預設'
L.DrawState_always = '始終'
L.DrawState_never = '從不'

-- Rules
L.Rules = '規則'
L.RulesDesc = '設定將哪個主題套用到不同的介面元素'
L.RuleEnabled = '已啟用'
L.RuleEnabledDesc = '啟用或停用此規則'
L.RuleTheme = '主題'
L.RuleThemeDesc = '選擇此規則符合時要套用的主題'

-- Builtin Rule Names
L.Rule_action = '動作按鈕'
L.Rule_action_charge = '動作按鈕 - 充能'
L.Rule_action_loc = '動作按鈕 - 失去控制'
L.Rule_blizzard_zone = '區域技能'
L.Rule_blizzard_nameplates = '名牌'
L.Rule_everything = '其他所有'
